name: build-image

on:
  push:
    branches:
      - 'v2/chain/deweb/testnet'
      - 'v2/chain/deweb/mainnet'
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/deweb-services/bdjuno:latest