name: Docker Image CI

on:
  push:
    branches: [ v2/chains/deweb/mainnet ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bdjuno:mainnet$(date +%s)
